urls.py
# from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.defaults import *
from ajax_select import urls as ajax_select_urls
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mydb.views.home', name='home'),
    # url(r'^mydb/', include('mydb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^parse/',include('wiki_parser.urls')),
    url(r'^music/',include('movie_music.urls')),
    url(r'^ajx/',include('ajx.urls')),
    url(r'^v2/',include('indexv2.urls')),
    url(r'^v1/',include('indexv1.urls')),
    url(r'^mobile/v1/',include('mobile_api_v1.urls')),

    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
  #  url(r'^movie/(?P<movie_id>\d+)/$','movies.views.movie_detail'),
  #http://127.0.0.1:8000/movie/15-None/
   url(r'^movie/15-(.)?','index.views.movie_default_page'),
   # url(r'^footer/$','index.views.footer',name='footer'),
   # url(r'^footer/2/$','index.views.footer2',name='footer2'),
   # url(r'^getanotherimage/$','index.views.diff_back_img',name='diff_back_img'),
)
urlpatterns += patterns('contribute.views',
     url(r'^user/contribute/$','contribute_info'),
)

urlpatterns += patterns('movies.views',

    # url(r'^movie/all/$','movie_list_all'),
    url(r'^movie/search/$','movie_search'),
    url(r'^movie/searching/', 'movie_searching'),
    # url(r'^add/movie/entermovie/', 'movie_enter',name='movie_enter'), #verifying status 
    # url(r'^add/movie/enteringmovie/', 'movie_entering'), #verifying
    ###############################
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/$','movie_detail_plot',name='movie_detail_plot'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/rating/$','movie_detail_rating',name='movie_detail_rating'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/cast/$','movie_detail_cast'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/music/$','movie_detail_music'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/trailers/$','movie_detail_trailers'),

    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/index/$','movie_detail_index',name='movie_detail_index'),
    ###############################
	)

urlpatterns += patterns('movie_news.views',
        # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/news/$','movie_detail_news',name='movie_detail_news'),
        # url(r'^news/(?P<news_id>\d+)/$','news_detail',name='news_detail'),
    )

urlpatterns += patterns('movie_music.views',
            # url(r'^add/movie_music/ajaxaddurl/$', 'ajaxaddurl'), #anyone can add this for now
            )


urlpatterns += patterns('user_votes.views',
            # url(r'^movie/(?P<movie_id>\d+)/ajaxrating/', 'ajaxrate'),
            )

urlpatterns += patterns('user_profile.views',
   # url(r'^user/register/$','user_register'),
    #url(r'^user/registering/$','user_registering'),
    #url(r'^user/login/$','user_login'),
   # url(r'^user/loging/$','user_loging'),
  #  url(r'^user/logout/$','user_logout',name='logout'),    
   # url(r'^user/pagex/$','page_x'),
)

urlpatterns += patterns('images.views',
     # url(r'^image/background/all/$','back_images_all'),
     # url(r'^image/background/(?P<image_id>\d+)/$','back_image'),
    # url(r'^image/list/$','listview',name='listview'),
    # url(r'^image/listurl/$','listview_url',name='listview_url'),
    # url(r'^image/(?P<image_id>\d+)/$','image_view'),
    # url(r'^image/(?P<image_id>\d+)/ajaxtaging/$','image_tag'),
    # url(r'^image/(?P<movie_id>\d+)\-?([^/]?)+/(?P<image_id>\d+)/$','image_movie_view'),
    # url(r'^image/(?P<movie_id>\d+)\-?([^/]?)+/$','image_movie_view_all'),
    # url(r'^person/image/(?P<person_id>\d+)\-?(.?)+/(?P<image_id>\d+)/$','person_detail_image'),
    # url(r'^person/image/(?P<person_id>\d+)\-?(.?)+/$','person_detail_images'),
    # url(r'^profile/image/(?P<person_id>\d+)\-?(.?)+/(?P<image_id>\d+)/$','profile_detail_image'),
    # url(r'^image/background/(?P<movie_id>\d+)\-?([^/]?)+/(?P<image_id>\d+)/$','back_image_movie_view'),
    # url(r'^image/background/all/(?P<movie_id>\d+)\-?([^/]?)+/$','back_image_movie_view_all'),
    )

urlpatterns += patterns('movie_casting.views',
    # url(r'^add/cast/addcast/(?P<movie_id>\d+)\-?([^/]?)+/$','addcast'), #verifying
    # url(r'^add/cast/addingcast/(?P<movie_id>\d+)\-?([^/]?)+/$','addingcast'), #verifying
    )

urlpatterns += patterns('professions.views',
    url(r'^profession/searching/', 'profession_searching'),
    # url(r'^add/profession/addprof/$', 'add_prof'), #verifying
    )

urlpatterns += patterns('index.views',
    #url(r'^$','main_page',name="index"),
    url(r'^main/$','main_page',name="index_main"), #home button uses this
    url(r'^$','releasing',name="index"),
    # url(r'^add/$', 'add_page'),
    # url(r'^list/$', 'list_page'),
    # url(r'^movies/latest/theaters/$','latest_theaters',name="latest_theaters"),
    url(r'^movies/latest/trailers/$','latest_trailers',name="latest_trailers"),
    # url(r'^movies/latest/db/$','latest_db',name="latest_db"),
    # url(r'^movies/latest/releasing/$','releasing',name="releasing"),
    url(r'^movies/latest/news/$','latest_news',name="latest_news"),
    # url(r'^all/searching/$','all_searching',name="all_searching"), #ajax call
    # url(r'^search/all/$','search_all',name="search_all"),
    )

urlpatterns += patterns('movie_persons.views',
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/info/$','person_detail_info',name="person_detail_info"),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/movies/$','person_detail_movies'),
    #url(r'^person/(?P<person_id>\d+)\-?(.?)+/music/$','person_detail_music'),
    #url(r'^person/(?P<person_id>\d+)\-?(.?)+/$','person_detail_info'),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/$','person_detail_index'),
    # url(r'^add/person/addperson/$','enter_person'), #verifying
    # url(r'^add/person/(?P<person_id>\d+)\-?(.?)+/$','edit_person',name='edit_person_url'), #verifying
    
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/index/$','person_detail_index',name='person_detail_index'),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/trailers/$','person_detail_trailers',name='person_detail_trailers'),
    url(r'^person/searching/', 'person_searching'),
    # url(r'^person/all/$', 'movie_persons_listall',name='movie_persons_listall'),
    )

urlpatterns += patterns('user_profile.views',
        url(r'^user/profile/$','user_profile_main',name="user_profile_main"),
       # url(r'^user/profile/redirect/$','redirect_page',name="redirect_page"),
        )
urlpatterns += patterns('',
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',name="user_logout"),
    url(r'', include('social_auth.urls')),
    )+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
# Create your models here.


class movies(models.Model):
	movie_name=models.CharField(max_length=40,unique=True)
	movie_year=models.DateField(blank=True,null=True,default='1800-01-01')
	movie_plot=models.CharField(max_length=500,blank=True,null=True)
	movie_summary=models.CharField(max_length=5000,blank=True,null=True)
	movie_info=models.TextField(blank=True)
	def __unicode__(self):
		return self.movie_name
	
	def get_absolute_url(self):
		# url="/movie/"+str(self.id)+"-"+str(self.movie_name)+"/index/"  #old
		url="/v1/#/movie/"+str(self.id)+"/"+str(self.movie_name)+"/"
		return url


class telugu_movie(models.Model):
	movie_id = models.ForeignKey(movies)
	tel_movie_name=models.CharField(max_length=40,unique=True,null=True,blank=True)

	def __unicode__(self):
		return self.tel_movie_name +"--" +str(self.movie_id.movie_name)

class movie_dates(models.Model):
	movie_date=models.DateField(default=None)
	movie_id=models.ForeignKey(movies)
	desc = models.CharField(max_length=2000,blank=True,null=True)

class movie_extra_info(models.Model):
	fieldone=models.CharField(max_length=500)
	fieldtwo=models.CharField(max_length=500)
	movie_id=models.ForeignKey(movies)

	def __unicode__(self):
		return self.movie_id.movie_name+"--"+self.fieldone+"=="+self.fieldtwo

class movie_theater_status(models.Model):
	movie_id=models.ForeignKey(movies, unique=True)
	RELEASE_CHOICES = (
		(u'T',u'In Theaters'),
		(u'F',u'Not In Theaters'),
		(u'D',u'Going To Release')
		)
	release_status=models.CharField(max_length=2,choices=RELEASE_CHOICES)

	def __unicode__(self):
		return self.movie_id.movie_name+"---"+self.release_status

movies/forms.py
from django import forms
from django.contrib.admin import widgets 
import datetime

class enter_movie_form(forms.Form):
	movie_name=forms.CharField(max_length=40)
	movie_year=forms.DateField(initial=datetime.datetime.now(),widget=widgets.AdminDateWidget)
	movie_plot=forms.CharField(max_length=200,initial='Not Known')#,widget=forms.Textarea(attrs={'cols': 5, 'rows': 5}))
	movie_summary=forms.CharField(max_length=5000,initial='Not Known')
	movie_banner_image=forms.ImageField(required=False)
	movie_background_image=forms.ImageField(required=False)

movies/views/movie_enter.py
"""
movie name
release / released date
background image
plot

give colums for hero heroine's director

cast in movie ---- > enter cast on pop up window if they dont exist


"""
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from movies.forms import *
from movies.models import movies
from django.core.urlresolvers import reverse

from images.models import banner_images
from images.models import background_images
def movie_enter(request):
	#verifying is staff status here
	if request.user.is_authenticated():
		if request.user.is_staff:
			username=request.user.username
		else:
			return HttpResponse("user not staff click back on browser to go back")
	else:
		return HttpResponse("""login before to <a href=/user/login/>login here</a>""")
		
	p=enter_movie_form()
	return render_to_response('movies/templates/movie_enter.html',{'form':p},context_instance=RequestContext(request))

def movie_entering(request):

	f=enter_movie_form(request.POST)
	if f.is_valid():
		pass
	else:
		return HttpResponse("form data not valid")
	if request.method=='POST':
		#verifying is staff status here
		if request.user.is_authenticated():
			if request.user.is_staff:
				username=request.user.username
			else:
				return HttpResponse("user not staff click back on browser to go back")
		else:
			return HttpResponse("""login before to <a href=/user/login/>login here</a>""")
		new_movie=movies()
		new_movie_name=f.cleaned_data['movie_name']
		try:
			mo=movies.objects.get(movie_name__iexact=new_movie_name)
			return HttpResponse("movie with that name already exists")
		except:
			pass
		new_movie.movie_name=new_movie_name.title()
		new_movie.movie_year=f.cleaned_data['movie_year']
		new_movie.movie_plot=f.cleaned_data['movie_plot']
		new_movie.movie_summary=f.cleaned_data['movie_summary']
		new_movie.save()
		try:

			if request.FILES['movie_banner_image']:
				newbanner=banner_images(imagefile=request.FILES['movie_banner_image'])
				newbanner.user_id=request.user.id
				newbanner.user_level=9
				newbanner.movie_id=new_movie
				try:
					newbanner.save()
				except:
					new_movie.delete()
					return HttpResponse("error saving banner did not save movie either go back")
		except Exception,e:
			print e
		try:
			if request.FILES['movie_background_image']:
				newbackground=background_images(imagefile=request.FILES['movie_background_image'])
				newbackground.user_id=request.user.id
				newbackground.user_level=9
				newbackground.movie_id=new_movie
				try:
					newbackground.save()
				except:
					pass
				else:
					return HttpResponse("ERROR 2")
		except:
			pass
		movie_id=new_movie.id
		movie_name="-"+new_movie.movie_name
		return HttpResponseRedirect(reverse('movie_casting.views.addcast',  args=(movie_id,movie_name)))
			

movies/views/movie_search.py
import json
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from movies.models import movies
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from sorl.thumbnail import get_thumbnail
from images.models import banner_images
import random
def movie_search(request):
	return render_to_response('movies/templates/movie_search.html',context_instance=RequestContext(request))

def movie_searching(request):
	if request.is_ajax():
		q=request.GET.get('term','')
		moviez=movies.objects.filter(movie_name__icontains=q)[:10]
		results=[]
		for movie in moviez:
			movie_json={}
			movie_json['id']=movie.id
			movie_json['label']=movie.movie_name
			movie_json['value']=movie.movie_name
			movie_json['movie_id']=movie.id
			movie_json['url']="/movie/"+str(movie.id)+"-"+movie.movie_name+"/index/"
			try:
				this_movie_banner_images=banner_images.objects.filter(movie_id=movie.id)
				this_movie_banner_img=random.choice(this_movie_banner_images)
				this_movie_banner_image=this_movie_banner_img.imagefile
				movie_json['icon'] = get_thumbnail(this_movie_banner_image, '40x40', quality=99).url
				#print movie_json['icon']
			except banner_images.DoesNotExist:
				movie_json['icon']=''
			except Exception, e:
				#print e
				movie_json['icon']=''

			
			results.append(movie_json)
		data=json.dumps(results)
	else:
		data='fail'
	mimetype='application/json'
	return HttpResponse(data, mimetype)

movies/views/movies_list_all.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from movies.models import movies
from movie_ratings.models import movie_ratings
#import json
from images.models import banner_images
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def movie_list_all(request):
	items_per_page=30
	if request.user.is_authenticated():
		last_login = request.session.get('social_auth_last_login_backend')
	else:
		last_login=''
	
	try:
		if request.GET['p']:
			page_number=int(request.GET['p'])
		else:
			page_number=1
	except Exception, e:
		page_number=1

	page=page_number

	try:
		movies_list=movies.objects.all()[::-1]
		results=[]
	except movies.DoesNotExist:
		movies_list=''
	
	paginator = Paginator(movies_list,items_per_page)

	try:
		all_movies = paginator.page(page)
	except PageNotAnInteger:
		all_movies = paginator.page(1)
	except EmptyPage:
		all_movies = paginator.page(paginator.num_pages)

	for movie in all_movies:
		movie_json={}
		movie_json['name']=movie.movie_name
		movie_json['id']=movie.id
		try:
			this_movie_banner_images=banner_images.objects.filter(movie_id=movie.id)
			this_movie_banner_img=random.choice(this_movie_banner_images)
			movie_json['banner_image']=this_movie_banner_img
		except banner_images.DoesNotExist:
			movie_json['banner_image']=''
		except:
			movie_json['banner_image']=''

		try:
			movie_json['rating']=movie_ratings.objects.get(movie_id=movie.id).movie_rating
		except:
			movie_json['rating']="DoesNotExist"
		movie_json['year']=movie.movie_year.year
		results.append(movie_json)
	#movie_list=json.dumps(results)
	movie_list=results
	#print movie_list
	if request.user.is_authenticated():
		username=request.user.username
	else:
		username=""
	return render_to_response('movies/templates/movie_list_all.html',
								{
								'movies_list':movie_list,
								  'username':username,
								  'last_login':last_login,
								'all_movies':all_movies,
								
								},								
								context_instance=RequestContext(request)
							)

movies/templates/movie_detail_cast.html
{%extends "index_base_page.html"%}
{%block content2%}
<script type="text/javascript">
    window.setTimeout("location=('/v1/');",2000);
</script>
<script type="text/javascript">
  document.title = "{{name}} - Project Movies"
</script>
<div class="container-fluid">
  <div class="row-fluid">
  <div class="subnav-fixed subnav">
          <ul class="nav nav-pills">
              <li><a href="/movie/{{movie_id}}-{{name}}/index/{%if request.GET.iframe%}?iframe=1{%endif%}">{{name}}</a></li>
              <li><a href="{% url movie_detail_plot movie_id|add:"-" name %}{%if request.GET.iframe%}?iframe=1{%endif%}">Plot</a></li>
              <li><a href="{% url movie_detail_rating movie_id|add:"-" name %}{%if request.GET.iframe%}?iframe=1{%endif%}">Rating</a></li>
              <li><a href="/image/{{movie_id}}-{{name}}/{%if request.GET.iframe%}?iframe=1{%endif%}">Images</a></li>
              <li class="active" ><a href="/movie/{{movie_id}}-{{name}}/cast/{%if request.GET.iframe%}?iframe=1{%endif%}">Cast</a></li>
              <li><a href="/movie/{{movie_id}}-{{name}}/music/{%if request.GET.iframe%}?iframe=1{%endif%}">Music</a></li>
              <li><a href="/movie/{{movie_id}}-{{name}}/trailers/{%if request.GET.iframe%}?iframe=1{%endif%}">Trailers</a></li>
              <li><a href="{% url movie_detail_news movie_id|add:"-" name %}{%if request.GET.iframe%}?iframe=1{%endif%}">News</a></li>
    
          </ul>
  </div>
  
  <br/><br/>

<div>
    <div class="span8">

    
{%load thumbnail%}
{%for each_person in persons %}

<div class='cast_box_main'>
     <div class='cast_box_image' id="cast_box_image_id_{{forloop.counter}}">
            {% if each_person.profile_image %}

                    {% thumbnail each_person.profile_image.imagefile "80x80" crop='center' as image %}

                   <img src="{{ image.url }}" style="" />
                      {% endthumbnail %}
            {%else%}
                   
                    {% thumbnail "template_images/no_image.jpg" "80x80" crop='center' as image %}
                      <img src="{{ image.url }}" style="" />
                   {% endthumbnail %}
                   
            {%endif%}
      </div>    
            <div class='cast_box_content' id="cast_box_content_id_{{forloop.counter}}">
              <div class='cast_box_content_name'>
                <a href="{% url person_detail_index each_person.id '-'|add:each_person.name %}">{{each_person.name}}</a> 
                </div>      
                
                <div class='cast_box_content_prof'>    
                        {% for profession in each_person.professions %} 
                            <a href="/prof/{{profession.id}}/">{{profession.name}}</a>

                        {% endfor %} 
                </div>
                    
                  <div class='cast_box_content_char'>
                      {% if each_person.character%}
                      <a href="/char/{{each_person.character_id}}/">{{each_person.character}}</a>
                      {%endif%}
                  </div>

            </div>
</div>               
 {% endfor %}
    

      
</div>
  <div class="fb-comments span4" data-href="http://db.w4rlock.in{% url movie_detail_plot movie_id|add:"-" name %}" data-num-posts="2" data-width="370" ></div>
</div>

   </div>
  </div>

    <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=411415555554087";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<style type="text/css">
  .cast_box_main{
    width: 250px;
    height: 80px;
    margin: 5px;
    overflow: hidden;
    float: left;
    background: white;
    white-space: nowrap;
    -webkit-box-shadow: 0px 2px 4px #EEE;
        -moz-box-shadow: 0px 2px 4px #EEE;
        -o-box-shadow: 0px 2px 4px #EEE;
        box-shadow: 0px 2px 4px #EEE;
  }
  .cast_box_image{
    float: left;
    max-width: 50%;
  }
  .cast_box_content{
    float: right;
    width: 165px;
  }
  .cast_box_content_char{
    width: 100%
  }
  .cast_box_content_prof{
      width: 100%;
  } 
  
  .cast_box_content_name{
        width: 100%;
  } 
  .cast_box_content_name a{
    color: black;
    margin: 0;
    font-family: inherit;
    font-weight: bold;
    color: inherit;
    text-rendering: optimizelegibility;
    text-overflow: ellipsis;
  }
  .cast_box_main:hover{
    background: rgba(255, 255, 255, 0.5);
  }
  .cast_box_content_char a{
    text-rendering: optimizelegibility;
    text-overflow: ellipsis;
  }
  .cast_box_content_prof a{
     text-rendering: optimizelegibility;
    text-overflow: ellipsis;
  }
</style>

   {%endblock%}

movies/templates/movie_detail_raw.html
Name:
{% if name %}
	{{name}}
	<br/>
	{% if username %}
	 username: {{username}}&nbsp;&nbsp;<a href="/user/logout/">log out</a>
	 <br/>
	 Your Rating: {{ user_rating }} 
	 {% else %}
	 None Logedin
	 <br/><a href="/user/login/">login here</a>
	 {% endif %}
	 <br/>
	{% if rating %}
		<ul>
			{% for r in rating %}
				<li>Rating:{{r.star_rating}}</li>
				<li>No Votes: {{r.num_votes}}</li>
			{% endfor %}
		</ul>
	{% else %}
		<p> no rating data avliable</p>
	{% endif %}

	<form action="/movie/{{name.id}}/grating/" method="POST">
		{% csrf_token %}
		<input type="radio" name="rating" id="1" value="1" />
		<input type="radio" name="rating" id="2" value="2" />
		<input type="radio" name="rating" id="3" value="3" />
		<input type="radio" name="rating" id="4" value="4" />
		<input type="radio" name="rating" id="5" value="5" />
		<input type="radio" name="rating" id="6" value="6" />
		<input type="radio" name="rating" id="7" value="7" />
		<input type="radio" name="rating" id="8" value="8" />
		<input type="radio" name="rating" id="9" value="9" />
		<input type="radio" name="rating" id="10" value="10" />
		<input type="submit" value="Rate"/>
	</form>
{% else %}
	<p> no hel data avliable</p>
{% endif %}

Genre:
{% if genres %}
	<ul>
		{% for a in genres %}
			<li>{{a.movie_genres_type.movie_genre_type}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p> no hel data avliable</p>
{% endif %}

<br/>
<br/>

Cast:
{% if persons %}
	<ul>
		{% for b in persons %}
			<li><a href="/person/{{b.person_id.id}}/">{{b.person_id.person_name}}</a>&nbsp&nbsp {{b.profession_id.profession_name}}</li>
		{% endfor %}
	</ul>
{% else %}
	<p> no hel data avliable</p>
{% endif %}

movies/templates/movie_enter.html
<!-- List of uploaded documents -->
{%extends "movie_base_page.html"%}
{%block content%}
<script type="text/javascript">
function addFormField() {
    var id = document.getElementById("id").value;
    $("#divTxt").append("<p id='row" + id + "'><label for='txt" + id + "'>Field " + id + "&nbsp;&nbsp;<input type='text' name=name"+id+" size='20' id='txt" + id + "'>&nbsp;&nbsp<a href='#' onClick='removeFormField(\"#row" + id + "\"); return false;'>Remove</a><p>");
    
    
    id = (id - 1) + 2;
    document.getElementById("id").value = id;
}

function removeFormField(id) {
    $(id).remove();
}
</script>
<script type="text/javascript">
   jQuery(function() {
       jQuery("#id_movie_year").datepicker({
       											changeMonth: true,
												changeYear: true,
       											dateFormat: 'yy-mm-dd' ,
       											yearRange: '1930:2020'
       										});
   });
</script>
<style type="text/css">
#id_movie_plot {
    border:0;
 	font-family: Arial,Helvetica,sans-serif;
 	font-size: 167%;
 	color: #800000;
 	height:38px;
	padding:10px 0px 0px 10px;
 	vertical-align:middle;
 	width:352px;
}
#id_movie_year{
    border:0;
 	font-family: Arial,Helvetica,sans-serif;
 	font-size: 167%;
 	color: #800000;
 	height:38px;
	padding:10px 0px 0px 10px;
 	vertical-align:middle;
 	width:352px;
}
#id_movie_name{
    border:0;
 	font-family: Arial,Helvetica,sans-serif;
 	font-size: 167%;
 	color: #800000;
 	height:38px;
	padding:10px 0px 0px 10px;
 	vertical-align:middle;
 	width:352px;
}
#id_movie_summary{
    border:0;
 	font-family: Arial,Helvetica,sans-serif;
 	font-size: 167%;
 	color: #800000;
 	height:38px;
	padding:10px 0px 0px 10px;
 	vertical-align:middle;
 	width:352px;
}
</style>
<body>
  <div class="span9">
<div class="row-fluid">

<!--<p><a href="#" onClick="addFormField(); return false;">Add</a></p> -->
<form action="/add/movie/enteringmovie/" method="POST" id="form1" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
<!--<input type="hidden" id="id" value="1"> -->
<div id="divTxt">
</div>
<p><input type="submit" value="Submit" name="submit" class="btn">
<input type="reset" value="Reset" name="reset" class="btn"></p>
</form>

 <br/>
    <br/>
    Add Links:<br/>
    <a href="/image/list/">add image</a><br/>
    <a href="/add/movie/entermovie/">add movie</a><br/>
    <a href="/add/cast/addcast/">add cast for a moivie</a><br/>
    <a href="/add/person/addperson/">add person</a><br/>
</div>
</div>

{%endblock%}

movies/templates/movie_search.html
<link rel="stylesheet" href="{{ STATIC_URL }}jquery-ui.css" type="text/css" media="all" />
<script src="{{ STATIC_URL }}jquery.min.js" type="text/javascript"></script> 
<script src="{{ STATIC_URL }}jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(function() {
  $("#movies").autocomplete({
    source: "/movie/searching/",
    minLength: 2,
  });
});
</script>

<div class="ui-widget">
  <label for="movies">Movie: </label>
  <input id="movies">
</div>