urls.py
# from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.defaults import *
from ajax_select import urls as ajax_select_urls
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mydb.views.home', name='home'),
    # url(r'^mydb/', include('mydb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^parse/',include('wiki_parser.urls')),
    url(r'^music/',include('movie_music.urls')),
    url(r'^ajx/',include('ajx.urls')),
    url(r'^v2/',include('indexv2.urls')),
    url(r'^v1/',include('indexv1.urls')),
    url(r'^mobile/v1/',include('mobile_api_v1.urls')),

    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
  #  url(r'^movie/(?P<movie_id>\d+)/$','movies.views.movie_detail'),
  #http://127.0.0.1:8000/movie/15-None/
   url(r'^movie/15-(.)?','index.views.movie_default_page'),
   # url(r'^footer/$','index.views.footer',name='footer'),
   # url(r'^footer/2/$','index.views.footer2',name='footer2'),
   # url(r'^getanotherimage/$','index.views.diff_back_img',name='diff_back_img'),
)
urlpatterns += patterns('contribute.views',
     url(r'^user/contribute/$','contribute_info'),
)

urlpatterns += patterns('movies.views',

    # url(r'^movie/all/$','movie_list_all'),
    url(r'^movie/search/$','movie_search'),
    url(r'^movie/searching/', 'movie_searching'),
    # url(r'^add/movie/entermovie/', 'movie_enter',name='movie_enter'), #verifying status 
    # url(r'^add/movie/enteringmovie/', 'movie_entering'), #verifying
    ###############################
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/$','movie_detail_plot',name='movie_detail_plot'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/rating/$','movie_detail_rating',name='movie_detail_rating'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/cast/$','movie_detail_cast'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/music/$','movie_detail_music'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/trailers/$','movie_detail_trailers'),

    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/index/$','movie_detail_index',name='movie_detail_index'),
    ###############################
	)

urlpatterns += patterns('movie_news.views',
        # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/news/$','movie_detail_news',name='movie_detail_news'),
        # url(r'^news/(?P<news_id>\d+)/$','news_detail',name='news_detail'),
    )

urlpatterns += patterns('movie_music.views',
            # url(r'^add/movie_music/ajaxaddurl/$', 'ajaxaddurl'), #anyone can add this for now
            )


urlpatterns += patterns('user_votes.views',
            # url(r'^movie/(?P<movie_id>\d+)/ajaxrating/', 'ajaxrate'),
            )

urlpatterns += patterns('user_profile.views',
   # url(r'^user/register/$','user_register'),
    #url(r'^user/registering/$','user_registering'),
    #url(r'^user/login/$','user_login'),
   # url(r'^user/loging/$','user_loging'),
  #  url(r'^user/logout/$','user_logout',name='logout'),    
   # url(r'^user/pagex/$','page_x'),
)

urlpatterns += patterns('images.views',
     # url(r'^image/background/all/$','back_images_all'),
     # url(r'^image/background/(?P<image_id>\d+)/$','back_image'),
    # url(r'^image/list/$','listview',name='listview'),
    # url(r'^image/listurl/$','listview_url',name='listview_url'),
    # url(r'^image/(?P<image_id>\d+)/$','image_view'),
    # url(r'^image/(?P<image_id>\d+)/ajaxtaging/$','image_tag'),
    # url(r'^image/(?P<movie_id>\d+)\-?([^/]?)+/(?P<image_id>\d+)/$','image_movie_view'),
    # url(r'^image/(?P<movie_id>\d+)\-?([^/]?)+/$','image_movie_view_all'),
    # url(r'^person/image/(?P<person_id>\d+)\-?(.?)+/(?P<image_id>\d+)/$','person_detail_image'),
    # url(r'^person/image/(?P<person_id>\d+)\-?(.?)+/$','person_detail_images'),
    # url(r'^profile/image/(?P<person_id>\d+)\-?(.?)+/(?P<image_id>\d+)/$','profile_detail_image'),
    # url(r'^image/background/(?P<movie_id>\d+)\-?([^/]?)+/(?P<image_id>\d+)/$','back_image_movie_view'),
    # url(r'^image/background/all/(?P<movie_id>\d+)\-?([^/]?)+/$','back_image_movie_view_all'),
    )

urlpatterns += patterns('movie_casting.views',
    # url(r'^add/cast/addcast/(?P<movie_id>\d+)\-?([^/]?)+/$','addcast'), #verifying
    # url(r'^add/cast/addingcast/(?P<movie_id>\d+)\-?([^/]?)+/$','addingcast'), #verifying
    )

urlpatterns += patterns('professions.views',
    url(r'^profession/searching/', 'profession_searching'),
    # url(r'^add/profession/addprof/$', 'add_prof'), #verifying
    )

urlpatterns += patterns('index.views',
    #url(r'^$','main_page',name="index"),
    url(r'^main/$','main_page',name="index_main"), #home button uses this
    url(r'^$','releasing',name="index"),
    # url(r'^add/$', 'add_page'),
    # url(r'^list/$', 'list_page'),
    # url(r'^movies/latest/theaters/$','latest_theaters',name="latest_theaters"),
    url(r'^movies/latest/trailers/$','latest_trailers',name="latest_trailers"),
    # url(r'^movies/latest/db/$','latest_db',name="latest_db"),
    # url(r'^movies/latest/releasing/$','releasing',name="releasing"),
    url(r'^movies/latest/news/$','latest_news',name="latest_news"),
    # url(r'^all/searching/$','all_searching',name="all_searching"), #ajax call
    # url(r'^search/all/$','search_all',name="search_all"),
    )

urlpatterns += patterns('movie_persons.views',
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/info/$','person_detail_info',name="person_detail_info"),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/movies/$','person_detail_movies'),
    #url(r'^person/(?P<person_id>\d+)\-?(.?)+/music/$','person_detail_music'),
    #url(r'^person/(?P<person_id>\d+)\-?(.?)+/$','person_detail_info'),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/$','person_detail_index'),
    # url(r'^add/person/addperson/$','enter_person'), #verifying
    # url(r'^add/person/(?P<person_id>\d+)\-?(.?)+/$','edit_person',name='edit_person_url'), #verifying
    
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/index/$','person_detail_index',name='person_detail_index'),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/trailers/$','person_detail_trailers',name='person_detail_trailers'),
    url(r'^person/searching/', 'person_searching'),
    # url(r'^person/all/$', 'movie_persons_listall',name='movie_persons_listall'),
    )

urlpatterns += patterns('user_profile.views',
        url(r'^user/profile/$','user_profile_main',name="user_profile_main"),
       # url(r'^user/profile/redirect/$','redirect_page',name="redirect_page"),
        )
urlpatterns += patterns('',
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',name="user_logout"),
    url(r'', include('social_auth.urls')),
    )+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie_persons/models.py
from django.db import models

# Create your models here.

class movie_persons(models.Model):
	GENDER_CHOICES = (
		(u'M',u'Male'),
		(u'F',u'Female'),
		(u'G',u'Gay'),
		)
	person_name=models.CharField(max_length=400)
	person_gender=models.CharField(max_length=2,choices=GENDER_CHOICES)
	person_date_of_birth=models.DateField(blank=True,null=True,default='1800-01-01')
	person_bio=models.CharField(max_length=2000)
	person_sp=models.CharField(max_length=40,blank=True,null=True)
	person_info = models.TextField(blank=True)
	def __unicode__(self):
		return self.person_name

	def get_absolute_url(self):
		url="/person/"+str(self.id)+"-"+str(self.person_name)+"/index/"
		return url


class alternate_names(models.Model):
	person_id=models.ForeignKey(movie_persons)
	alternate_name=models.CharField(max_length=100)

class extra_info(models.Model):
	person_id=models.ForeignKey(movie_persons)
	fieldone=models.CharField(max_length=400)
	fieldtwo=models.CharField(max_length=2000)

movie_persons/forms.py
from django import forms
from django.contrib.admin import widgets 
import datetime
from movie_persons.models import movie_persons
class addmovie_persons(forms.Form):
	GENDER_CHOICES = (
		(u'M',u'Male'),
		(u'F',u'Female'),
		(u'G',u'Gay'),
		)
	person_name=forms.CharField(max_length=400)
	person_gender=forms.ChoiceField(choices=GENDER_CHOICES)
	person_date_of_birth=forms.DateField(required=False,initial='1800-01-01',widget=widgets.AdminDateWidget)
	person_bio=forms.CharField(max_length=2000)
	person_sp=forms.CharField(max_length=40,required=False,initial="Unknown")
	imagefile=forms.ImageField(label='select an image',help_text='max 42 megabytes',required=False)

	def clean_person_name(self):
		person_name = self.cleaned_data['person_name']
		test_person=movie_persons()
		try:
			test_person=movie_persons.objects.get(person_name=person_name)
		except test_person.DoesNotExist:
			return person_name
		raise forms.ValidationError(u'%s already exists' % person_name)

class edit_person_form(forms.Form):
	person_date_of_birth=forms.DateField(required=False,initial='1800-01-01',widget=widgets.AdminDateWidget)
	person_bio=forms.CharField(max_length=2000,widget=forms.Textarea)
	imagefile=forms.ImageField(label='select an image',help_text='max 42 megabytes',required=False)

indexv1/views/persons_list_all.py
from django.http import HttpResponse
from urlparse import urlparse
from django.shortcuts import render_to_response
from django.template import RequestContext
from images.models import background_images
from movie_music.models import *
from movies.models import movies

from movie_trailers.models import movie_trailers
from images.models import banner_images
from movie_genres.models import movie_genres
from genres.models import genres
from movie_persons.models import movie_persons
from movie_casting.models import movie_casting
from professions.models import professions
from movies.models import movie_theater_status
from images.models import profile_images

import random
import json
import re

from datetime import *
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.csrf import requires_csrf_token
from django.views.decorators.csrf import ensure_csrf_cookie

# movie_id=7
# url= "http://127.0.0.1:8000/api/mif/"+movie_id+"/"
# $.getJSON(url,function(data){console.log(data)})


from sorl.thumbnail import get_thumbnail
PERSON_BANNER_SIZE = '150x200'
MOVIE_BANNER_THUMBS_SIZE = '40x40'


from movie_persons.models import movie_persons
from movie_casting.models import movie_casting
from images.models import profile_images

@ensure_csrf_cookie
@requires_csrf_token
@csrf_protect
def persons_list_all(request):
	# if request.is_ajax():
	result = {}
	result['persons'] = []
	mimetype='application/json'
	all_persons = movie_persons.objects.all()[::-1]

	for each_person in all_persons:
		person_id = each_person.id

		person_json={}

		try:
			person=movie_persons.objects.get(id=person_id)
		except Exception, e:
			result_json='none'
			return HttpResponse(result_json,mimetype)

		person_json['id']=person.id
		person_json['name']=person.person_name
		person_json['gender'] = person.person_gender
		person_json['bio']=person.person_bio

		try:
			this_person_profile_image = random.choice(profile_images.objects.filter(person_id=person_id))
			person_json['profile_image'] = this_person_profile_image.imagefile.url
			if(this_person_profile_image.imagefile.width > 150):
				person_json['profile_image_small']=get_thumbnail(this_person_profile_image.imagefile,PERSON_BANNER_SIZE,crop='center').url
			else:
				person_json['profile_image_small']= get_thumbnail('template_images/no_image.jpg', PERSON_BANNER_SIZE, crop='top').url
		except Exception, e:
			person_json['profile_image']= get_thumbnail('template_images/no_image.jpg', PERSON_BANNER_SIZE, crop='top').url
			person_json['profile_image_small']= get_thumbnail('template_images/no_image.jpg', PERSON_BANNER_SIZE, crop='top').url
		try:
			person_bio_x=person.person_bio.replace('<p>','')
			person_bio_x=person_bio_x.replace('</p>','')
			person_json['bio_small']=person_bio_x[:190]
		except Exception, e:
			person_json['bio_small']=person.person_bio[:190]
		
		this_person_movies = movie_casting.objects.filter(movie_persons_id=person_id)
		this_person_movies = list(set(this_person_movies))
		movie_json=[]
		for each_movie in this_person_movies:
			this_movie_json={}
			this_movie_json['id']=each_movie.movie_id.id
			this_movie_json['name']=each_movie.movie_id.movie_name
			try:
				this_movie_banner_image = random.choice(banner_images.objects.filter(movie_id=each_movie.movie_id.id))
				this_movie_json['banner_image'] = this_movie_banner_image.imagefile.url
				this_movie_json['banner_image_small'] = get_thumbnail(this_movie_banner_image.imagefile,MOVIE_BANNER_THUMBS_SIZE,crop='top').url
			except Exception, e:
				this_movie_json['banner_image']	= get_thumbnail('template_images/no_image.jpg', MOVIE_BANNER_THUMBS_SIZE, crop='top').url
				this_movie_json['banner_image_small']	= get_thumbnail('template_images/no_image.jpg', MOVIE_BANNER_THUMBS_SIZE, crop='top').url
			movie_json.append(this_movie_json)
		person_json['movies']=movie_json[::-1]
		
		result['persons'].append(person_json)
	# result = person_json
	result_json=json.dumps(result)
	return HttpResponse(result_json,mimetype)
	
	# return HttpResponse('fail')

movie_persons/templates/edit_person.html
{%extends "movie_base_page.html"%}
{%block content%}
<div class="span12">
<script type="text/javascript">
   jQuery(function() {
       jQuery("#id_person_date_of_birth").datepicker({
                                                changeMonth: true,
                                                changeYear: true,
                                                dateFormat: 'yy-mm-dd' ,
                                                yearRange: '1930:2020'
                                            });
   });
   </script>
{%if user.username%}
{{user.username}}
{%if user.is_staff%}
is eligble to do this ---- 
<a href='{{global_var.admin_url}}movie_persons/movie_persons/{{person_id}}/'>edit on admin</a> -- 
{%else%}
is not eligble to do this
{%endif%}
{%else%}
none is logged in . you will not be able to perform this action
{%endif%}
<br/>
<br/>
You are editing data of - <h6>{{person_name}}</h6>
{%if updated_person%}
<br/>{{updated_person}}
{%endif%}
<form method="post" action="/add/person/{{person_id}}-{{person_name}}/" enctype="multipart/form-data">
{%csrf_token%}

    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.person_date_of_birth.errors }}
        <label for="id_person_date_of_birth">dob:</label>
        {{ form.person_date_of_birth }}
    </div>
     <div class="fieldWrapper">
        {{ form.person_bio.errors }}
        <label for="id_person_bio">bio:</label>
        <br/>{{ form.person_bio }}
    </div>
    <div class="fieldWrapper">
        {{ form.imagefile.errors }}
        <label for="id_imagefile">person_image:</label>
        {{ form.imagefile }}
    </div>
    
<input type="submit" name="submit" value="submit">
</form>

{%if images%}
already existing profile images:<br/>
 {%load thumbnail%}
 {%for each_image in images%}
        {% thumbnail each_image.imagefile "160x120" as image %}
             <img src="{{image.url}}" alt="some-thing-is-wrong-with-connection"> 
          
        {%endthumbnail%}
{%endfor%}
{%endif%}
</div>

{%endblock%}

movie_persons/templates/enter_person.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>{{movie_name}}</title>
<script src="{{ MEDIA_URL }}jquery.min.js" type="text/javascript"></script> 
<link rel="stylesheet" href="{{ MEDIA_URL }}jquery-ui.css" type="text/css" media="all" />
<script src="{{ MEDIA_URL }}jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(function() {
  $("#id_person_name").autocomplete({
    source: "/person/searching/",
    minLength: 2,
  });
});

$(function() {
  $("#id_person_profession").autocomplete({
    source: "/profession/searching/",
    minLength: 2,
  });
});
</script>
<script type="text/javascript">
   jQuery(function() {
       jQuery("#id_person_date_of_birth").datepicker({
                                                changeMonth: true,
                                                changeYear: true,
                                                dateFormat: 'yy-mm-dd' ,
                                                yearRange: '1930:2020'
                                            });
   });
   </script>
</head>
{%if added_person %}
sucessfully added {{added_person}}
{%endif%}
<h1> {{movie_name}}</h1>
<form action="/add/person/addperson/" method="post" enctype="multipart/form-data">
	{%csrf_token%}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.person_name.errors }}
        <label for="id_person_name">person_name:</label>
        {{ form.person_name }}
    </div>
    <div class="fieldWrapper">
        {{ form.person_gender.errors }}
        <label for="id_person_gender">person gender:</label>
        {{ form.person_gender }}
    </div>
    <div class="fieldWrapper">
        {{ form.person_date_of_birth.errors }}
        <label for="id_person_date_of_birth">dob:</label>
        {{ form.person_date_of_birth }}
    </div>
    <div class="fieldWrapper">
        {{ form.person_bio.errors }}
        <label for="id_person_bio">bio:</label>
        {{ form.person_bio }}
    </div>
    <div class="fieldWrapper">
        {{ form.person_sp.errors }}
        <label for="id_person_sp">sp:</label>
        {{ form.person_sp }}
    </div>
    <div class="fieldWrapper">
        {{ form.imagefile.errors }}
        <label for="id_imagefile">person_image:</label>
        {{ form.imagefile }}
    </div>
    <p><input type="submit" value="Add Persn" /></p>
</form>


    <br/>
    <br/>
    Add Links:<br/>
    <a href="/image/list/">add image</a><br/>
    <a href="/add/movie/entermovie/">add movie</a><br/>
    <a href="/add/cast/addcast/">add cast for a moivie</a><br/>
    <a href="/add/person/addperson/">add person</a><br/>

</html>`

movie_persons/templates/person_detail_index.html
    {%extends "index_base_page.html"%}
{%block content2%}
<script type="text/javascript">
  document.title = "{{name}} - Project Movies"
</script>
<div class="container-fluid">
  <div class="row-fluid">
  <div class="subnav-fixed subnav">
          <ul class="nav nav-pills">
            
  <li class="active"><a href="{% url person_detail_index name.id '-'|add:name.person_name %}{%if request.GET.iframe%}?iframe=1
{%endif%}">{{name.person_name}}</a></li>
             <li><a href="/person/{{name.id}}-{{name.person_name}}/info/{%if request.GET.iframe%}?iframe=1
{%endif%}">Info</a></li>
              <li><a href="/person/{{name.id}}-{{name.person_name}}/movies/{%if request.GET.iframe%}?iframe=1
{%endif%}">Movies</a></li>
              <li><a href="/person/image/{{name.id}}-{{name.person_name}}/{%if request.GET.iframe%}?iframe=1
{%endif%}">Images</a></li>
              <li><a href="/person/{{name.id}}-{{name.person_name}}/music/{%if request.GET.iframe%}?iframe=1
{%endif%}">Music</a></li>
          <li><a href="{% url person_detail_trailers name.id '-'|add:name.person_name %}{%if request.GET.iframe%}?iframe=1
{%endif%}">Trailers</a></li>
              <li><a href="#">News</a></li>

          </ul>
  </div>
  <br/><br/>   
  <div id="alert" class="alert fade in" data-dismiss="alert" href="#">
            <span id="tag_note_message">
              {%if request.GET.alert%}
              {{request.GET.alert}}
              {%else%}
              <script type="text/javascript">
              document.getElementById("alert").className+=" hide";
              </script>
              {%endif%}
            </span>

            </div>
   
    <div class="info_box span11">
        

        <div class="span10 info_box_style removeopacity" id='infobox_qlinks'>&nbsp;&nbsp;&nbsp;
           <a href="/person/{{name.id}}-{{name.person_name}}/info/">Info</a>&nbsp;&nbsp;&nbsp;
            <a href="/person/{{name.id}}-{{name.person_name}}/movies/">Movies</a>&nbsp;&nbsp;&nbsp;
            <a href="/person/image/{{name.id}}-{{name.person_name}}/">Images</a>&nbsp;&nbsp;&nbsp;
            <a href="/person/{{name.id}}-{{name.person_name}}/music/">Music</a>&nbsp;&nbsp;&nbsp;
          <a href="{% url person_detail_trailers name.id '-'|add:name.person_name %}">Trailers</a>&nbsp;&nbsp;&nbsp;
              <a href="#">News</a>
        </div>

        
<div class="span11">
        <div class="span1" style='text-align:center;'>
        <a href="#">
            <img src="{{profile_image.imagefile.url}}" id='profile_image' style="max-height: 80px; padding-bottom: 10px; padding-top: 10px;" >

          </a>
          </div>
<div class="info_box_style removeopacity span11">
{%load thumbnail%}
   
    <div class="span4">
    <a href="{% url person_detail_info name.id '-'|add:name.person_name %}">
      <h5>{{name.person_name}}</h5></a>
      {%if alternate_names%}
      [
      {%for alternate_name in alternate_names%}
      {{alternate_name.alternate_name}} 
      {%endfor%}
      ]
      {%endif%}
              <p>
                {%if person_professions%}
                {%for profession in person_professions%}
                <a href="/profession/{{profession.id}}/">{{profession.profession_name}}</a> /
                {%endfor%}
                {%endif%}
      
              </p>
    </div>
      <div class="span4">
              In Movies: 
             {% for each_movie in person_movies %}
             {% if each_movie.back_image %}
                         {% thumbnail each_movie.back_image.imagefile "40x35" as image %}
      
                  <a href="{% url movie_detail_index each_movie.movie.id '-'|add:each_movie.movie.movie_name %}" rel="tooltip" title="{{each_movie.movie.movie_name}}">
                   <img src="{{ image.url }}" style="padding:{{ image|margin:"40x35" }}" />
                 </a>
      
                        {% endthumbnail %}
                   
                      {%else%}
             <a href="{% url movie_detail_index each_movie.movie.id '-'|add:each_movie.movie.movie_name %}">{{each_movie.movie.movie_name}}</a> /
                      {%endif%}

             {%endfor%}
            </div>            
            
            <div class="span4">
              {% if name.person_date_of_birth.year == 1800 %}
              {%else%}
              <p>
                Birth Date: {{name.person_date_of_birth}}
              </p>
              {%endif%}
             
                {%if name.person_bio%}
                 <p>
              Bio:  {{name.person_bio|truncatechars:125}}
              <a href='{% url person_detail_info name.id '-'|add:name.person_name %}'>Read More</a>
              </p>
               {%endif%}
              
            </div>            

           

</div>

</div>
<div class="span12">
  
</div>
    </div>

  </div>
</div>
<style type="text/css">
 
.removeopacity{
    opacity: 1;
    -moz-opacity: 1;
    filter:alpha(opacity=10);
    bottom: 50px;
}
.info_box_style{
  
  color: rgb(255,255,255);
  font-size: 13px;
  
}
  .info_box{
    background-color: black;
    
    opacity: 0.8;
    -moz-opacity: 0.8;
    filter:alpha(opacity=8);
    
  }
  #page_body{
   /* background:url({{profile_image.imagefile.url}});
     background:url('http://127.0.0.1:8000/media/image/2012/4/4/9d781e54-56a8-434d-b80f-4ce6e21cb153.jpg'); */
    background-repeat:repeat;  
    background-attachment:fixed;
/*
    -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  */  
  }

@media (min-width: 980px) {
  .info_box{
    position: absolute;
    bottom: 50px;
  }
  #page_footer{
  position: fixed;
  bottom: 0px;
}
}
@media (max-width: 780px){
  #infobox_qlinks{
    display: none;
  }
}

</style>
<script type="text/javascript">
window.onload = function(e){ 
  profile_image=$('#profile_image');
  naturalwidth = profile_image[0].naturalWidth;
  naturalheight = profile_image[0].naturalHeight;
  if (naturalwidth<500 & naturalheight<500){
  $("#page_body").css("background-image", "url('{{MEDIA_URL}}template_images/back_repeat2.jpg')");
}else{
  $("#page_body").css("background-image", "url('{{profile_image.imagefile.url}}')");
}
}
        
</script>
    
{% endblock %}

movie_persons/templates/person_details_info.html
{%extends "movie_base_page.html"%}

{%block content%}

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">{% if name %} {{name.person_name}}{%else%}Does Not Exist{%endif%}</li>
              <li class="active"><a href="/person/{{name.id}}-{{name.person_name}}/info/">Info</a></li>
              <li><a href="/person/{{name.id}}-{{name.person_name}}/movies/">Movies</a></li>
              <li><a href="/media/person/image/{{name.id}}-{{name.person_name}}/">Images</a></li>
              <li><a href="/person/{{name.id}}-{{name.person_name}}/music/">Music</a></li>
              <li><a href="#">Trailers</a></li>
              <li><a href="#">News</a></li>
            </ul>
          </div>
    </div>
    <div class="span9">
     <div class="row-fluid">
      <div class="span3">
     {% load thumbnail %}
    {% if profile_image %}
    
    <a href=""><img src="{{profile_image.imagefile.url}}" alt="Insert Logo Here" name="Insert_logo" width="180" id="Insert_logo" /></a>
    
   
   {%else%}
   {%if random_profile_image%}
   {% thumbnail random_profile_image.imagefile "180x200" as image %}
    <a href=""><img src="{{ image.url }}" style="padding:{{ image|margin:"180x200" }}"></a>
    {% endthumbnail %} 
   {%else%}
   {% thumbnail "http://127.0.0.1:8000/media/image/nouser.jpg" "180x200" as image %}
                   <img src="{{ image.url }}" style="padding:{{ image|margin:"180x200" }}" />
            {% endthumbnail %} 
    {%endif%}
   {%endif%}
 </div>
 <div class="span3">

    <h2>{% if name %} {{name}}{%else%}Does Not Exist{%endif%}</h2>
        <p> {% if person_professions %}
              {% for a in person_professions %}<a href="/profession/{{a.id}}/">{{a.profession_name}}</a>&nbsp;
              {% endfor %}
          {% else %} 
            None
          {% endif %}</p>
       </div>
       <div class="span9">   
            <p>
                <strong>Bio:</strong>
                {{name.person_bio}}
            </p>
          
        </div>

      </div>
    </div>
  </div>
</div>
    
{% endblock %}