urls.py
# from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.defaults import *
from ajax_select import urls as ajax_select_urls
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mydb.views.home', name='home'),
    # url(r'^mydb/', include('mydb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^parse/',include('wiki_parser.urls')),
    url(r'^music/',include('movie_music.urls')),
    url(r'^ajx/',include('ajx.urls')),
    url(r'^v2/',include('indexv2.urls')),
    url(r'^v1/',include('indexv1.urls')),
    url(r'^mobile/v1/',include('mobile_api_v1.urls')),

    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
  #  url(r'^movie/(?P<movie_id>\d+)/$','movies.views.movie_detail'),
  #http://127.0.0.1:8000/movie/15-None/
   url(r'^movie/15-(.)?','index.views.movie_default_page'),
   # url(r'^footer/$','index.views.footer',name='footer'),
   # url(r'^footer/2/$','index.views.footer2',name='footer2'),
   # url(r'^getanotherimage/$','index.views.diff_back_img',name='diff_back_img'),
)
urlpatterns += patterns('contribute.views',
     url(r'^user/contribute/$','contribute_info'),
)

urlpatterns += patterns('movies.views',

    # url(r'^movie/all/$','movie_list_all'),
    url(r'^movie/search/$','movie_search'),
    url(r'^movie/searching/', 'movie_searching'),
    # url(r'^add/movie/entermovie/', 'movie_enter',name='movie_enter'), #verifying status 
    # url(r'^add/movie/enteringmovie/', 'movie_entering'), #verifying
    ###############################
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/$','movie_detail_plot',name='movie_detail_plot'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/rating/$','movie_detail_rating',name='movie_detail_rating'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/cast/$','movie_detail_cast'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/music/$','movie_detail_music'),
    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/trailers/$','movie_detail_trailers'),

    # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/index/$','movie_detail_index',name='movie_detail_index'),
    ###############################
	)

urlpatterns += patterns('movie_news.views',
        # url(r'^movie/(?P<movie_id>\d+)\-?([^/]?)+/news/$','movie_detail_news',name='movie_detail_news'),
        # url(r'^news/(?P<news_id>\d+)/$','news_detail',name='news_detail'),
    )

urlpatterns += patterns('movie_music.views',
            # url(r'^add/movie_music/ajaxaddurl/$', 'ajaxaddurl'), #anyone can add this for now
            )


urlpatterns += patterns('user_votes.views',
            # url(r'^movie/(?P<movie_id>\d+)/ajaxrating/', 'ajaxrate'),
            )

urlpatterns += patterns('user_profile.views',
   # url(r'^user/register/$','user_register'),
    #url(r'^user/registering/$','user_registering'),
    #url(r'^user/login/$','user_login'),
   # url(r'^user/loging/$','user_loging'),
  #  url(r'^user/logout/$','user_logout',name='logout'),    
   # url(r'^user/pagex/$','page_x'),
)

urlpatterns += patterns('images.views',
     # url(r'^image/background/all/$','back_images_all'),
     # url(r'^image/background/(?P<image_id>\d+)/$','back_image'),
    # url(r'^image/list/$','listview',name='listview'),
    # url(r'^image/listurl/$','listview_url',name='listview_url'),
    # url(r'^image/(?P<image_id>\d+)/$','image_view'),
    # url(r'^image/(?P<image_id>\d+)/ajaxtaging/$','image_tag'),
    # url(r'^image/(?P<movie_id>\d+)\-?([^/]?)+/(?P<image_id>\d+)/$','image_movie_view'),
    # url(r'^image/(?P<movie_id>\d+)\-?([^/]?)+/$','image_movie_view_all'),
    # url(r'^person/image/(?P<person_id>\d+)\-?(.?)+/(?P<image_id>\d+)/$','person_detail_image'),
    # url(r'^person/image/(?P<person_id>\d+)\-?(.?)+/$','person_detail_images'),
    # url(r'^profile/image/(?P<person_id>\d+)\-?(.?)+/(?P<image_id>\d+)/$','profile_detail_image'),
    # url(r'^image/background/(?P<movie_id>\d+)\-?([^/]?)+/(?P<image_id>\d+)/$','back_image_movie_view'),
    # url(r'^image/background/all/(?P<movie_id>\d+)\-?([^/]?)+/$','back_image_movie_view_all'),
    )

urlpatterns += patterns('movie_casting.views',
    # url(r'^add/cast/addcast/(?P<movie_id>\d+)\-?([^/]?)+/$','addcast'), #verifying
    # url(r'^add/cast/addingcast/(?P<movie_id>\d+)\-?([^/]?)+/$','addingcast'), #verifying
    )

urlpatterns += patterns('professions.views',
    url(r'^profession/searching/', 'profession_searching'),
    # url(r'^add/profession/addprof/$', 'add_prof'), #verifying
    )

urlpatterns += patterns('index.views',
    #url(r'^$','main_page',name="index"),
    url(r'^main/$','main_page',name="index_main"), #home button uses this
    url(r'^$','releasing',name="index"),
    # url(r'^add/$', 'add_page'),
    # url(r'^list/$', 'list_page'),
    # url(r'^movies/latest/theaters/$','latest_theaters',name="latest_theaters"),
    url(r'^movies/latest/trailers/$','latest_trailers',name="latest_trailers"),
    # url(r'^movies/latest/db/$','latest_db',name="latest_db"),
    # url(r'^movies/latest/releasing/$','releasing',name="releasing"),
    url(r'^movies/latest/news/$','latest_news',name="latest_news"),
    # url(r'^all/searching/$','all_searching',name="all_searching"), #ajax call
    # url(r'^search/all/$','search_all',name="search_all"),
    )

urlpatterns += patterns('movie_persons.views',
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/info/$','person_detail_info',name="person_detail_info"),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/movies/$','person_detail_movies'),
    #url(r'^person/(?P<person_id>\d+)\-?(.?)+/music/$','person_detail_music'),
    #url(r'^person/(?P<person_id>\d+)\-?(.?)+/$','person_detail_info'),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/$','person_detail_index'),
    # url(r'^add/person/addperson/$','enter_person'), #verifying
    # url(r'^add/person/(?P<person_id>\d+)\-?(.?)+/$','edit_person',name='edit_person_url'), #verifying
    
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/index/$','person_detail_index',name='person_detail_index'),
    # url(r'^person/(?P<person_id>\d+)\-?(.?)+/trailers/$','person_detail_trailers',name='person_detail_trailers'),
    url(r'^person/searching/', 'person_searching'),
    # url(r'^person/all/$', 'movie_persons_listall',name='movie_persons_listall'),
    )

urlpatterns += patterns('user_profile.views',
        url(r'^user/profile/$','user_profile_main',name="user_profile_main"),
       # url(r'^user/profile/redirect/$','redirect_page',name="redirect_page"),
        )
urlpatterns += patterns('',
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',name="user_logout"),
    url(r'', include('social_auth.urls')),
    )+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

contribute/models.py
from django.db import models

# Create your models here.
from movies.models import movies
from movie_persons.models import movie_persons
from django.contrib.auth.models import User
import datetime
import uuid
import os

def get_file_path(instance,filename):
	ext=filename.split('.')[-1]
	filename="%s.%s" % (uuid.uuid4(),ext)
	return os.path.join(instance.directory_string_var,filename)

class data_text(models.Model):
	movie_id=models.ForeignKey(movies,blank=True,null=True)
	person_id=models.ForeignKey(movie_persons,blank=True,null=True)
	user_id=models.ForeignKey(User)
	text=models.CharField(max_length=5000)
	added_date = models.DateTimeField(auto_now_add=True, blank=True)
	def __unicode__(self):
		output=''
		try:
			output=output+self.movie_id.movie_name
		except Exception, e:
			pass
		try:
			output=output+self.person_id.person_name
		except Exception, e:
			pass
		return output


class data_image(models.Model):
	movie_id=models.ForeignKey(movies,blank=True,null=True)
	person_id=models.ForeignKey(movie_persons,blank=True,null=True)
	user_id=models.ForeignKey(User) 
	imagefile=models.ImageField(upload_to=get_file_path)
	now=datetime.datetime.now()
	directory_string_var = 'image/%s/%s/%s/'%(now.year,now.month,now.day)
	added_date = models.DateTimeField(auto_now_add=True, blank=True)
	def __unicode__(self):
		output=''
		try:
			output=output+self.movie_id.movie_name
		except Exception, e:
			pass
		try:
			output=output+self.person_id.person_name
		except Exception, e:
			pass
		return output

contribute/forms.py
from django import forms
from django.contrib.admin import widgets 
import datetime
from movie_persons.models import movie_persons
from movies.models import movies

class contribute_form(forms.Form):
	person_id=forms.IntegerField(required=False,help_text='type name and choose from drop down we will select the id for you',widget=forms.TextInput(attrs={'placeholder':'None Selected',}))
	movie_id=forms.IntegerField(required=False,help_text='type name and choose from drop down we will select the id for you',widget=forms.TextInput(attrs={'placeholder':'None Selected',}))
	text=forms.CharField(max_length=5000,widget=forms.Textarea,required=False,help_text='max 5000 chars')
	imagefile=forms.ImageField(label='select an image ',help_text='max 42 megabytes',required=False)

	def clean_person_id(self):
		person_id = self.cleaned_data['person_id']
		if person_id==None:
			return person_id
		test_person=movie_persons()
		try:
			test_person=movie_persons.objects.get(id=person_id)
			return person_id
		except test_person.DoesNotExist:
			raise forms.ValidationError(u'person with id - %s does not exists' % person_id)

	def clean_movie_id(self):
		movie_id = self.cleaned_data['movie_id']
		if movie_id==None:
			return movie_id
		test_movie=movies()
		try:
			test_movie=movies.objects.get(id=movie_id)
			return movie_id
		except test_movie.DoesNotExist:
			raise forms.ValidationError(u'movie with id- %s does not exists' % movie_id)

	def clean(self):
		cleaned_data = super(contribute_form, self).clean()
		person_id = cleaned_data.get('person_id')
		movie_id = cleaned_data.get('movie_id')
		
		if person_id==None and movie_id==None:
			raise forms.ValidationError(u'Have to Choose Yetleast one from person and movie')
		else:
			return cleaned_data

movies/forms.py
from django import forms
from django.contrib.admin import widgets 
import datetime

class enter_movie_form(forms.Form):
	movie_name=forms.CharField(max_length=40)
	movie_year=forms.DateField(initial=datetime.datetime.now(),widget=widgets.AdminDateWidget)
	movie_plot=forms.CharField(max_length=200,initial='Not Known')#,widget=forms.Textarea(attrs={'cols': 5, 'rows': 5}))
	movie_summary=forms.CharField(max_length=5000,initial='Not Known')
	movie_banner_image=forms.ImageField(required=False)
	movie_background_image=forms.ImageField(required=False)

contribute/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from contribute.forms import contribute_form
from contribute.models import *
from movies.models import movies
from movie_persons.models import movie_persons
def contribute_info(request):
	status=''
	if request.user.is_authenticated():
		user=request.user
	else:
		return HttpResponse("""login before to <a href='/accounts/login/?next=/user/contribute/'>here</a>""")

	if request.method=='POST':
		form=contribute_form(request.POST,request.FILES)
		if form.is_valid():
			text=data_text()
			image=data_image()
			
			try:
				text.movie_id=movies.objects.get(id=form.cleaned_data['movie_id'])
				image.movie_id=movies.objects.get(id=form.cleaned_data['movie_id'])
			except Exception, e:
				status = status + 'No Movie'
			
			try:
				text.person_id=movie_persons.objects.get(id=form.cleaned_data['person_id'])
				image.person_id=movie_persons.objects.get(id=form.cleaned_data['person_id'])
			except Exception, e:
				status = status + 'No person'
			text.user_id=user
			image.user_id=user
			
			try:
				text.text=form.cleaned_data['text']
			except Exception, e:
				pass		

			try:
				if request.FILES['imagefile']:
					try:
						image.imagefile=request.FILES['imagefile']
						image.save()
						status = ' Image Saved. will be updated once confirmed'
					except Exception, e:
						print e
			except Exception, e:
				print e
			
			try:
				if text.text != '':
					text.save()
					status = status + ' Data Saved. will be updated once confirmed'
			except Exception, e:
				raise e
			form=contribute_form()

			return render_to_response('contribute/templates/contribute.html',
									{
									'sucess':'1',
									'status':status,
									'form':form
									},context_instance=RequestContext(request)
								)
	
		else:
			return render_to_response('contribute/templates/contribute.html',
									{
									'form':form,
									},context_instance=RequestContext(request)
								)
	
	else:
		try:
			if request.GET['person_id']:
				person_id=request.GET['person_id']
			else:
				person_id=''
		except Exception, e:
			person_id=''
		
		try:
			if request.GET['movie_id']:
				movie_id=request.GET['movie_id']
			else:
				movie_id=''
		except Exception, e:
			movie_id=''
		if movie_id=='' and person_id=='':
			form = contribute_form()
			return render_to_response('contribute/templates/contribute.html',
									{
									'form':form,
									},context_instance=RequestContext(request)
								)
		
		form = contribute_form(initial={'movie_id':movie_id,'person_id':person_id})
		return render_to_response('contribute/templates/contribute.html',
									{
									'form':form,
									},context_instance=RequestContext(request)
								)
		

contribute/templates/contribute.html
{%extends "movie_base_page.html"%}
{%block content%}
<div class="span12">
<script type="text/javascript">

$(function() {

    function log( message ) {
           $('#id_movie_name').html(message);
        }

$("#id_movie_id").autocomplete({
minLength: 2,
      source: "/movie/searching/",
      focus: function( event, ui ) {
        $( "#id_movie_id" ).val( ui.item.id );
       $('#id_movie_name').html('selected '+ui.item.label);
        return false;
      },
      select: function( event, ui ) {
                  { 
             $('#id_movie_name').html('selected [ '+ui.item.label+' ]');
                 $( "#id_movie_id" ).val( ui.item.id );
                 return false;      
        }   
      },
   
    })
    .data( "autocomplete" )._renderItem = function( ul, item ) {
      return $( "<li></li>" )
        .data( "item.autocomplete", item )
        .append( "<a><img src='"+item.icon+"'>&nbsp;"+ item.value + "</a>" )
        .appendTo( ul );
    };
  });
  </script>

  <script type="text/javascript">
$(function() {
  $("#id_person_id").autocomplete({
    source: "/person/searching/",
    minLength: 2,
    select: function( event, ui ) {
                  { 
             $('#id_person_name').html('selected [ '+ui.item.label+' ]');
                 $( "#id_person_id" ).val( ui.item.id );
                 return false;      
        }   
      },
  });
});
</script>


<br/>
<br/>
{%if sucess%}
<span class="label label-success">{{status|safe}}
</span>
<h6>contribute more ?</h6>
{%else%}
{%endif%}
{%if user.username%}
        contributing as <span class='label'>{{user.username}} [{{user.first_name}}-{{user.last_name}}].</span> your username will be recorded
        <p>
          <li>  Any Field can be empty but yetleast one person or movie has to be selected.</li>
        </p>
        
        <form method="post" action="/user/contribute/" enctype="multipart/form-data">
        {%csrf_token%}

         <span style='color: rgb(185, 74, 72)'>{{ form.non_field_errors }}</span>
            <div class="fieldWrapper">
                {{ form.person_id.errors }}
                <label for="id_person_id">Person id:</label>
                {{ form.person_id }}
                <span id="id_person_name"> Selected [ ]. [can be empty]</span>
                 <span class="help-inline">{{form.person_id.help_text}}</span>
            </div>
             <div class="fieldWrapper">
                {{ form.movie_id.errors }}
                <label for="for_id_movie_id" >Movie id:</label>
                <br/>{{ form.movie_id }}
                <span id="id_movie_name"> Selected [ ]. [can be empty]</span>
                 <span class="help-inline">{{form.movie_id.help_text}}</span>
            </div>
            <div class="fieldWrapper">
                {{ form.text.errors }}
                <label for="id_text">Info:</label>
                {{ form.text }}
                <span id="id_text">Cane be Empty</span>
                 <span class="help-inline">{{form.text.help_text}}</span>
            </div>
            <div class="fieldWrapper">
                {{ form.imagefile.errors }}
                <label for="id_imagefile">Image:</label>
                {{ form.imagefile }}
                <span id="id_imagefile">Cane be Empty</span>
                 <span class="help-inline">{{form.imagefile.help_text}}</span>
            </div>
            
        <input type="submit" name="submit" value="submit">
        </form>
        </div>
{%else%}
none is logged in . you will not be able to perform this action
{%endif%}




{%endblock%}

contribute/templates/contribute_sucess.html
{%extends "movie_base_page.html"%}
{%block content%}
<div class="span12">
<script type="text/javascript">

$(function() {

    function log( message ) {
           $('#id_movie_name').html(message);
        }

$("#id_movie_id").autocomplete({
minLength: 2,
      source: "/movie/searching/",
      focus: function( event, ui ) {
        $( "#id_movie_id" ).val( ui.item.id );
       $('#id_movie_name').html('selected '+ui.item.label);
        return false;
      },
      select: function( event, ui ) {
                  { 
             $('#id_movie_name').html('selected '+ui.item.label);
                 $( "#id_movie_id" ).val( ui.item.id );
                 return false;      
        }   
      },
   
    })
    .data( "autocomplete" )._renderItem = function( ul, item ) {
      return $( "<li></li>" )
        .data( "item.autocomplete", item )
        .append( "<a><img src='"+item.icon+"'>&nbsp;"+ item.value + "</a>" )
        .appendTo( ul );
    };
  });
  </script>

  <script type="text/javascript">
$(function() {
  $("#id_person_id").autocomplete({
    source: "/person/searching/",
    minLength: 2,
    select: function( event, ui ) {
                  { 
             $('#id_person_name').html('selected '+ui.item.label);
                 $( "#id_person_id" ).val( ui.item.id );
                 return false;      
        }   
      },
  });
});
</script>


<br/>
<br/>
{%if sucess%}
<h3>{{status}}</h3>
{%else%}

go here to submit
{%endif%}

{%endblock%}